### PR TITLE
feat: added necessary AS compiler to AS to make a AS transformer

### PR DESCRIPTION
**Pull request by willemneal**

### CODE REVIEW

**Comment by yjhmelody** [comment]
Why add such much code ?

**Comment by willemneal** [comment]
Because I copied the source files from the compiler.  Eventually the compiler will be broken up into more granular modules, but until then I just copied them here to compile to AS.

**Comment by yjhmelody** [comment]
It seems that assemblyscript did not upload the as version of the compiler part of the code

**Comment by yjhmelody** [comment]
@willemneal  Hi. In fact, I have not officially started this grant project, because assemblyscript does not seem to export the assemblyscript version of the compiler API.

**Comment by willemneal** [comment]
@yjhmelody That's why I copied them here. You don't need the full compiler API just the AST and transform API.  We should schedule a time to talk in more depth about this.

**Comment by yjhmelody** [comment]
@willemneal `transform` seems to currently only support nodejs. And I think the transform API really does not need to be done in an AST visitor library

**Comment by willemneal** [comment]
@yjhmelody:

Here are my thoughts on how to achieve this in the short term. For now, the compiler's frontend will continue to be in JS. So we need just one transform that this library will provide.

The outer transform will do the following:
- Find transforms in the AS code. For now we can consider them to be a class or function transformer.
- Find "call sites", e.g. `@serailizabe \n class`
- Compile the AS transforms, Pass the corresponding string of AST nodes in question perhaps via Wasi using stdin. The transform then prints to stdout the transformed source, which then again is parsed by the outer transform. There is definitely a better way of passing the data back and forth, but this seems to be the simplest.

**Comment by yjhmelody** [comment]
@willemneal 

Do you want to implement a pure AS version of transform? Why doesn't this wait for the official build-in?
I want to implement an as version of AST visitor alone, and there is no problem. But if we want to implement transform, we need to communicate more details, which is a bit unacceptable, and I think this should be implemented by the AS official, after all, the official has provided platform-independent Transform interfaces (like writeFile/readFile), but I seem to I do not see this piece of relevant progress.

And even if it really needs to be implemented, I personally think this can be completely split into 2 libs.

**Comment by willemneal** [comment]
@yjhmelody The more I think about it you are correct.  We should move this work and make a PR to the main repo.  I will be available early tomorrow for me.  If you can find me on discord we can sync on the next steps.  Otherwise I'll write up my ideas tomorrow morning.

**Comment by yjhmelody** [comment]
@willemneal  Well, I created a new repo https://github.com/yjhmelody/as-visitor

**Pull request closed without merging**
