### PR TITLE
make it work with AS 0.20.x

### PR DESCRIPTION
**Pull request by roaminroe**
I had to make quite a lot of changes to make it work with AS 0.20.x:
- move to NodeJS `module`
- remove the `as` folder completely
- one drawback to moving to  `module` is that I haven't been able to lake the unit tests work, but the package works as it is running in the `@as-covers` module

### CODE REVIEW

**Comment by roaminroe** [comment]
I haven't been able to make the tests work with typescript with neither jest or mocha, however, I was able to make the tests work with mocha using javascript (jest just won't work, it's not able to load the esm modumes for some reason)

**Comment by willemneal** [comment]
Hey @roaminroe Sorry I missed this! Looking into this now.

**Comment by willemneal** [comment]
Hey @roaminroe Sorry I missed this! Looking into this now.

**Comment by jtenner** [comment]
@roaminroe can we set up some time to chat on discord? I am taking over development of the large majority of these tools to bring them up to speed, and would like your help and input because of the incredibly large effort you have already made.

**Pull request merged**
